### PR TITLE
feat(parser): allow paths to have collons

### PR DESCRIPTION
**Pull request by wedneyyuri**
Query using keys containing `:` (ex: `zoom_rels:skus`) was not working:

```
from skus
with product = 5664807
only _embedded.zoom_rels:skus.id

from offers
with sku = skus._embedded.zoom_rels:skus.id
only _embedded.zoom_rels:offers.id, _embedded.zoom_rels:offers.name
```

### CODE REVIEW

**Comment by caiorcferreira** [comment]
Nice addition, thank you!

Could you add at least one test case for this scenario?

You can add them to the `ast_test.go` file. You can see a sample test for variables [here](https://github.com/b2wdigital/restQL-golang/blob/1bfecc88cab33a62860c684d11032fa7aa536284/internal/parser/ast/ast_test.go#L138).

**Comment by wedneyyuri** [comment]
Hi @caiorcferreira, thanks for the recommendation, I'm trying to understand why it affected other test cases.

I'm not familiar with this type of setup, can you help me understand if this is the place that needs to be changed to fix the case I created?

**Review by wedneyyuri — COMMENTED** [review]
solved

**Comment by wedneyyuri** [comment]
Made the requested changes, it's ready for review again :)

**Review by caiorcferreira — APPROVED** [review]

**Comment by caiorcferreira** [comment]
Sorry for taking so long to answer. 
You nailed it, the colon in the `IDENT` rule would conflict with the use of it as a key/value separator in an object value.

Thank you for the PR!

**Pull request merged**
